### ISSUE TITLE
Polling interval in Home Assistant

### ISSUE THREAD

**Issue by mskorge** [persandstrom/python-verisure#103]
Hi, and thanks for a great HA module!
Lately in Sweden Verisure has started blocking people polling faster than every 30 minutes. They are sending an email telling people they will remain blocked until the polling rate is lowered. 
I would love to see polling interval as an optional configuration setting so I can set it lower myself instead of having to modify the code.

Keep up the good work!

**Comment by xibriz** [comment]
Interesting... I wounder if they will do this in Norway also. I'm so close to just dropping Verisure because I think they are quite expensive. If they block me that will be the last drop :)

**Comment by krambriw** [comment]
I use this python module since long and my understanding is that you can decide yourself the polling interval if you write a small python script using it.
But, ouch, if we get blocked, what to do? 30 minutes makes it useless. So far I have not received any email yet, been polling every 15 second since the beginning (on the other hand I informed them when I started, at that time had my own similar python solution using web scraping before switching to Per's module)
I use this interface for integration with my HA system based on Node-RED. It is clear that Verisure is moving their focus towards home automation in combination with home alarm systems. This makes sense I think but I personally would like to keep my HA system separated. Currently I use the 3 arm states ('ARMED_HOME', 'ARMED_AWAY', 'DISARMED') and smartplug part. It would be really bad if all this leads in a way that you have to overcome by building a HW interface based on 2 smartplugs + some I/O supported by the HA system just to get the arm state into the same.
Best would be if Verisure could provide a public api but I guess this will not happen considering their increasing interest in HA by themselves

All this leads me to think about another issue listed, Push messages #57. Has anyone looked into this further? I read about the emulator idea. One idea could be to run Android on a dedicated RPi, having the Verisure app installed. But then, I would think best would be to interface with an MQTT broker in someway to publish state changes & accept commands from the HA system

Any ideas?

**Comment by krambriw** [comment]
Provided using Android, could this be interesting for python???
[](https://www.youtube.com/watch?v=8Jwp1PTvECI)

**Comment by mskorge** [comment]
Thanks a lot for spending some time on this! Will help us out for sure...

**Comment by krambriw** [comment]
> "I don't know if Android offer other apps to 'listen to' notifications from other apps"
Maybe is possible:
https://stackoverflow.com/questions/26731306/android-is-it-possible-to-get-other-apps-notification-info
