### ISSUE TITLE
new version in home assistant

### ISSUE THREAD

**Issue by christian-ek** [persandstrom/python-verisure#74]
Hi,
Didn't know how to contact you so I created an issue here.
I am wondering if it's your code that is used from Home Assistant Verisure component?
If so, can it be updated to your latest version? Would love to have the door sensors in Home Assistant.

BR,
Christian

**Comment by persandstrom** [comment]
Hi, 
It's an older version of python-verisure that is used by home assistant. 
My plan is to update HA, I have been a bit occupied lately though.
Hopefully I will get the time/energy to do it soon.

**Comment by xprezz** [comment]
It would be great if you could find the time. With the latest updates to HA it seems the smartplugs are broken. Also thank you for the great work :)

**Comment by persandstrom** [comment]
I have started to update HA now, will probably take a bit more. 
https://github.com/persandstrom/home-assistant/tree/vsure_app_api

**Comment by xprezz** [comment]
Thank you so much!

**Comment by persandstrom** [comment]
If anyone has a yale lock, some python skills and some time over, please take a look at my PR. I have some problems getting it to be responsive enough.

[https://github.com/persandstrom/home-assistant/tree/vsure_app_api]()

**Comment by Redferne** [comment]
I have a Yale lock, HA, spare time and a little python skill. What do you need?

**Comment by persandstrom** [comment]
@Redferne Great!
I don't have lock myself so I have a hard time trying to fix some issues with it. 
It seems like it takes a long time from when the lock is locked until the overview is updated with the new lock status. 
I need some help trying to solve this in a good way in HA. 

If you clone my [branch ](https://github.com/persandstrom/home-assistant/tree/vsure_app_api) and see if you can get it up and running. Try locking and unlocking and see if you experience the issue. 

The file you should look in is primarily: `homeassistant/components/lock/verisure.py` 
and the methods: `set_lock_state` and `update`

If you have any questions about the code, or need to reason you can IM me on gitter

**Comment by Redferne** [comment]
@persandstrom

It is enough to copy your changes to deps/verisure folder and restart HA. Or have you made other changes?

**Comment by persandstrom** [comment]
There are a lot of changes in HA, you need to use my home assistant branch in order to test

**Comment by Redferne** [comment]
Ok. Managed to get your changes patched to my hassbian and virtual env installation. Yes. The update of lock status is slow, it took at least 30 seconds from the time I manually locked until status was updated. I need to add a bunch of debug prints to investigate and compare against the Verisure Android app.  How often do you poll from the Verisure api?

**Comment by persandstrom** [comment]
The API is polled at most every minute if nothing else is stated.
To force an update you should call: ``` hub.update_overview(no_throttle=True)```

For reference you can look at the 
[alarm_control_panel implementation ](https://github.com/persandstrom/home-assistant/blob/vsure_app_api/homeassistant/components/alarm_control_panel/verisure.py)

As you can see here in ```set_arm_state``` the call to the API returnes a transactionID, that transaction ID is polled and when a result is given an update of the overview is forced. 

I expected the lock to work the same way, but something seems to be different.

**Comment by Redferne** [comment]
Well, since the get_overview() is default throttled to 60s. Updates from the Verisure API will be slow. Not sure if it is worth lowering the interval for the lock entity to 15s to get it a little more responsive? On a another note, I dumped the overview json for the locks:

```
[ {'secureModeActive': False,
 'method': 'REMOTE',
 'paired': True,
 'deviceLabel': 'xXxX xXxX',
 'lockedState': 'UNLOCKED',
 'currentLockState': 'UNLOCKED',
 'eventTime': '2017-06-17T16:42:38.000Z',
 'pendingLockState': 'NONE',
 'userString': 'Redferne',
 'area': 'xXxXxXx',
 'motorJam': False} ]
```
Could be interesting to forward **secureModeActive, method, eventTime, currentLockState, pendingLockState, motorJam** up to the lock entity so that the upper layers can make use of them?

What do you think?

**Comment by persandstrom** [comment]
When changing the lock state from the Verisure app or from the lock itself a delay on  60 seconds is expected. The reason for that is as you say that the overview is only updated every minute at most. 

If the lock state is changed by HA it should be possible to get a more responsive update, since we have the knowledge that it was changed. My hope is that the transaction id can be used in any way as it is in the alarm_control_panel. 

By the way, can ```pendingLockState``` be of interest?  Has that changed when the result OK is returned from lock transaction?

For the other fields, they might be interesting but that can be done in another PR after the basic functionality is working.

**Comment by Redferne** [comment]
Yes, there is something fishy here. It takes around a minute for the lock status to change even if explicitly updated with `hub.update_overview(no_throttle=True)`. The Android app is however updated as soon as it has refreshed. I'll have a look in the vsure library and maybe need to resort to tcpdump to figure this out :cry:

**Comment by persandstrom** [comment]
If you use the command line of vsure and change the lock and after that read overview, how long does it take for the status to change?

Maybe it is easier to figure out if you write a small script that imports verisure and then play around with the functions
```
get_lockstate
set_lockstate
get_lock_state_transaction
get_overview
```
just to get a feel about what happens when you set lock state and then read the lock state transaction.

**Comment by yada75** [comment]
I totally suck at python but hopefully this helps somehow.
We can't use transaction_id to verify or assume that state is changed.
If new set_lock_state is sent before currentLockState have changed then error with bad request.
Only diff in get_overview and get_lock_state is "zone": "004" is available in get_lock_state and in my 3 locks zone is 002,003,004 and i don't have verisure alarm.

Se attachment
[report.txt](https://github.com/persandstrom/python-verisure/files/1097556/report.txt)

**Comment by Redferne** [comment]
I've been tinkering with this the past week and have gotten as far as the get_overview is returning stale information. Lock transaction works fine here. However the last call to get_overview is not returning the new lock state, but the same data as before the lock transaction. I've tried adding no_throttle=True and also a forced logout() and login() to no avail. The new lock state is not returned  until 1 or even 2 minutes later. I'm wondering how the Android app is doing it's refresh. We might need to take a stab at running  apktool on the Verisure app and have a look at the java code?

**Comment by yada75** [comment]
I think some mixups made it in [`self._state = state`](https://github.com/persandstrom/home-assistant/blob/vsure_app_api/homeassistant/components/lock/verisure.py#L117) [link](https://github.com/persandstrom/home-assistant/blob/vsure_app_api/homeassistant/components/lock/verisure.py#L117)
In earlier version you set `STATE_LOCKED` and `STATE_UNLOCKED` to `self._state`
Now its `'lock'` and `'unlock'` to `self._state`

This would work i think?

```python
if state == 'lock':
    self._state = STATE_LOCKED
if state == 'unlock':
    self._state = STATE_UNLOCKED
```

But In my report of command line test of vsure, transaction_id is only some form of verification that `set_state` is sent to lock. Only `session.get_lock_state`or `session.get_overview`is true verification if locked or unlocked

**Comment by yada75** [comment]
Just leaving this error if state change is requested before `get_overview` is updated
`verisure.session.ResponseError: Invalid response, status code: 400 - Data: {"errorGroup":"BAD_REQUEST","errorCode":"VAL_00819","errorMessage":"The requested doorlock state is not possible to apply due to state already set"}`

**Comment by persandstrom** [comment]
@Redferne I have never used any tool like apktool, have you had any luck with that?  I have used [charles](https://www.charlesproxy.com/) for listening to the traffic from the android app.

@yada75 Good that it seems to work, but your changes has some flaws. 
The loop would be stuck if the state does not change, and  Verisure does not like that we send too many requests so I think that we shouldn't put a get_overview in a loop.

> Just leaving this error if state change is requested before get_overview is updated
verisure.session.ResponseError: Invalid response, status code: 400 - Data: {"errorGroup":"BAD_REQUEST","errorCode":"VAL_00819","errorMessage":"The requested doorlock state is not possible to apply due to state already set"}

Is that the response from set_lock_state or get_lock_state_transaction?

> I think some mixups made it in self._state = state link
In earlier version you set STATE_LOCKED and STATE_UNLOCKED to self._state
Now its 'lock' and 'unlock' to self._state

I have pushed some changes according to your suggestion here, if you have time please try this

**Comment by yada75** [comment]
@persandstrom I'm still learning but is `get_lock_state_transaction` a request also? and will loop until ok? That's why i suggested to skip transaction request and do `get_overview` instead with longer time intervals in between. 
> Is that the response from set_lock_state or get_lock_state_transaction?

Its from `set_lock_state` if verisure api server have `LOCKED` state and we send `'lock'`

I saw the change and looks promising, should work. But we really need to check if `UNLOCKED` before attempting to set `'lock'`

**Comment by yada75** [comment]
I might get this totally wrong but Is `STATE_UNLOCKED` in `def unlock(self, **kwargs):`actually used in `set_lock_state` ?

would this `lock_state = 'lock' if STATE_LOCKED else 'unlock'` just change the lock to the "other" locked/unlocked state?

**Comment by persandstrom** [comment]
>  I'm still learning but is get_lock_state_transaction a request also? and will loop until ok? 

It's a minimal request, and probably takes a very small resources from the server, that is how the app does it for the alarm (not sure about the lock but guess the behavior is the same). It will loop until a result is given for the transaction, whether it is OK or not. But you are right there should be a maximum number of tries, I will add that. 

> I might get this totally wrong but Is STATE_UNLOCKED in def unlock(self, **kwargs):actually used in set_lock_state ?

I see not that the code is bad :) , it should be 
```lock_state = 'lock' if state == STATE_LOCKED else 'unlock'```
since the there are only two desired states the lock_state will ```lock``` if state == STATE_LOCKED and ```unlock``` if STATE == STATE_UNLOCKED.


> But we really need to check if UNLOCKED before attempting to set 'lock'

An exception should be raised and the command aborted if the desired state is the same as the current state. Is this causing any problems? Should just be a red line in the log, right?

**Comment by yada75** [comment]
Totally slipped my mind, good thinking on transaction generally. I see now that transaction is preferred, example is if door is open then locked state will never happen in get_overview but transaction will be ok.

Later on we should consider some error reporting if transaction is ok but get_overview don't get expected state, like example above if door is open then locked state will never happen.

> An exception should be raised and the command aborted if the desired state is the same as the current state. Is this causing any problems? Should just be a red line in the log, right?

I will try to explain my automation again just to avoid misunderstanding. I have 3 locks and at 21:30 automation calls that all 3 locks should lock. If one lock is already locked then "some guard funktion" should not try to lock that door again. HA now sends lock request to all locks thru verisure component. I think this logic must be in HA or component and not in automation.yaml because it will be ridiculous long mix of conditions. You might nailed it but It's to late in the evening for me to grasp this logic but shouldn't it be `lock_state = 'lock' if state == STATE_UNLOCKED else 'unlock'`? need to sleep on that one :) In this example exception is not needed. Here is my automation.

```yaml
- id: Lock_evening
  alias: Lock evening
  hide_entity: true
  trigger:
  - platform: time
    at: '21:30:00'
  action:
  - service: lock.lock
    data:
      entity_id: group.all_locks
      code: 123456
```

I will do further thinking and testing later this week.

**Comment by Redferne** [comment]
Sorry for slow response, I've taken a few hours vacation :smile_cat:

I've not been able to find a nice solution for this issue but I've found a workaround. Set the request headers to disable caching in the verisure session api:
```
                headers={
                    .......
                    'Cache-Control': 'no-cache',
                    'Pragma': 'no-cache',
                    'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT',
                    .........
```
and force a update + relogin in the lock component:
```
    def update(self):
        """Update lock status."""
#        if time() - self._change_timestamp < 10:
#            return
        hub.update_overview(no_throttle=True, force=True)
```
which is triggered here in the hub component:
```
    @Throttle(timedelta(seconds=60))
    def update_overview(self, force=None):
        """Update the overview."""
        if force == True:
            self.logout()
            self.session._vid = None
            self.session._giid = None
            self.session.installations = None
            self.login()
```
Now the new lock state is updated with 3-4 seconds, which is quite OK. However it does not solve the lack of notifications, if the door is manually unlocked to let the cat in and then relock the door, HA will almost never get notified. But this requires some sort of push support in the backend. Hail websocket! :smirk:

**Comment by Redferne** [comment]
Also added this in lock->update to get a nice status string in HA:
```
        self._method = hub.get_first(
            "$.doorLockStatusList[?(@.deviceLabel=='%s')].method",
            self._device_label)
        self._time = hub.get_first(
            "$.doorLockStatusList[?(@.deviceLabel=='%s')].eventTime",
            self._device_label)
        self._changed_by = str(self._method) + " by " + str(hub.get_first(
            "$.doorLockStatusList[?(@.deviceLabel=='%s')].userString",
            self._device_label)) + " @ " + str(self._time)
```

**Comment by persandstrom** [comment]
@Redferne seems like you have done om great investigation here! Is the logout/login needed or is it possible to wait for a few seconds and then read using no-cache?

>  However it does not solve the lack of notifications, if the door is manually unlocked to let the cat in and then relock the door, HA will almost never get notified

Is the verisure-app notified when the lock status is manually changed?

**Comment by yada75** [comment]
@persandstrom Tried your last pull with (As you told me, triple check anything i say from now on) `lock_state = 'lock' if state == STATE_LOCKED else 'unlock'` and changed to `sleep(2.0)` in loop. Working great with max 4sec for state change. Good to go regarding response on my system.

@Redferne good hunting. Do you experience cache issues with commandline version also?
I never had any cache issues at all.
if i comments out like you did just to test.
```python
def update(self):
        """Update lock status."""
#        if time() - self._change_timestamp < 10:
#            return
```
then i get a additional delay for 4-10sec so total 8-14sec response. So i guess there is something here, HA issue? above my knowledge.

**Comment by yada75** [comment]
@persandstrom i was to fast with `lock_state = 'lock' if state == STATE_LOCKED else 'unlock'`

Could you just do something like this to be sure that lock is unlocked before try to lock for now. Plenty of time later to optimize?
```python
    def unlock(self, **kwargs):
        """Send unlock command."""
        if not self._state == STATE_LOCKED:
            return
        self.set_lock_state(kwargs[ATTR_CODE], 'unlock')

    def lock(self, **kwargs):
        """Send lock command."""
        if not self._state == STATE_UNLOCKED:
            return
        self.set_lock_state(kwargs[ATTR_CODE], 'lock')

    def set_lock_state(self, code, state):
        """Send set lock state command."""
        transaction_id = hub.session.set_lock_state(
            code,
            self._device_label,
            state)['doorLockStateChangeTransactionId']
        ...
        ...
```

**Comment by persandstrom** [comment]
> if time() - self._change_timestamp < 10 return is really needed. Right?

That is to coop with the delay, for 10 seconds after the state is changed we assume that the desired state is set (as long as the transaction was OK).

**Comment by persandstrom** [comment]
I have merged to home-assistant now, we can still try to improve/fix issues in a new PR.

**Comment by yada75** [comment]
Great work per :) Let breathe for a while

**Comment by christian-ek** [comment]
Wow, Thank you for your work!

**Comment by thomasbosoe** [comment]
Okay, this sounds good, but how do I get this implemented in HA, because I'm having the same issue with Yaleman lock (Verisure). When I enter my garage it takes up to nearly one minute before lights are turning on.
